
into_people_database_registration_register:
    path: /
    defaults: { _controller: "FOSUserBundle:Registration:register" }

into_people_database_registration_check_email:
    path: /check-email
    defaults: { _controller: "FOSUserBundle:Registration:checkEmail" }
    methods: "GET"

into_people_database_registration_confirm:
    path: /confirm/{token}
    defaults: { _controller: "FOSUserBundle:Registration:confirm" }
    methods: "GET"

into_people_database_registration_confirmed:
    path: /confirmed
    defaults: { _controller: "FOSUserBundle:Registration:confirmed" }
    methods: "GET"
