into_people_database_templateversion:
    resource: "@IntoPeopleDatabaseBundle/Resources/config/routing/templateversion.yml"
    prefix:   /templateversion

into_people_database_corequality:
    resource: "@IntoPeopleDatabaseBundle/Resources/config/routing/corequality.yml"
    prefix:   /corequality

into_people_database_systemmail:
    resource: "@IntoPeopleDatabaseBundle/Resources/config/routing/systemmail.yml"
    prefix:   /systemmail

into_people_database_user:
    resource: "@IntoPeopleDatabaseBundle/Resources/config/routing/user.yml"
    prefix:   /user

into_people_database_generalcycle:
    resource: "@IntoPeopleDatabaseBundle/Resources/config/routing/generalcycle.yml"
    prefix:   /generalcycle

into_people_database_default:
    resource: "@IntoPeopleDatabaseBundle/Resources/config/routing/default.yml"
    prefix:   /

into_people_database_myfeedbackcycle:
    resource: "@IntoPeopleDatabaseBundle/Resources/config/routing/myfeedbackcycle.yml"
    prefix:   /myfeedbackcycle

into_people_database_cdp:
    resource: "@IntoPeopleDatabaseBundle/Resources/config/routing/cdp.yml"
    prefix:   /cdp

into_people_database_midyear:
    resource: "@IntoPeopleDatabaseBundle/Resources/config/routing/midyear.yml"
    prefix:   /midyear

into_people_database_endyear:
    resource: "@IntoPeopleDatabaseBundle/Resources/config/routing/endyear.yml"
    prefix:   /endyear

into_people_database_feedbackcycle:
    resource: "@IntoPeopleDatabaseBundle/Resources/config/routing/feedbackcycle.yml"
    prefix:   /feedbackcycle

into_people_database_supervisor:
    resource: "@IntoPeopleDatabaseBundle/Resources/config/routing/supervisor.yml"
    prefix:   /supervisor

into_people_database_hr:
    resource: "@IntoPeopleDatabaseBundle/Resources/config/routing/hr.yml"
    prefix:   /hr

into_people_database_endyeartemplate:
    resource: "@IntoPeopleDatabaseBundle/Resources/config/routing/endyeartemplate.yml"
    prefix:   /endyeartemplate

into_people_database_midyeartemplate:
    resource: "@IntoPeopleDatabaseBundle/Resources/config/routing/midyeartemplate.yml"
    prefix:   /midyeartemplate

into_people_database_cdptemplate:
    resource: "@IntoPeopleDatabaseBundle/Resources/config/routing/cdptemplate.yml"
    prefix:   /cdptemplate

into_people_database_organization:
    resource: "@IntoPeopleDatabaseBundle/Resources/config/routing/organization.yml"
    prefix:   /organization

into_people_database_language:
    resource: "@IntoPeopleDatabaseBundle/Resources/config/routing/language.yml"
    prefix:   /language
cronjob:
    path:     /cronjob/{token}
    defaults: { _controller: IntoPeopleDatabaseBundle:Cronjob:cronjob }
